// Hearts => 1, 
// Spades => 2, 
// Clubs  => 3, 
// Diamonds  => 4
export default {
    cardValue: {
        'H-ace': {value: 1, url: '//deckofcardsapi.com/static/img/AH.png'},  
        'H-2': {value: 2, url: '//deckofcardsapi.com/static/img/2H.png'}, 
        'H-3' :{value: 3, url: '//deckofcardsapi.com/static/img/3H.png'}, 
        'H-4': {value: 4, url: '//deckofcardsapi.com/static/img/4H.png'},  
        'H-5': {value: 5, url: '//deckofcardsapi.com/static/img/5H.png'},  
        'H-6': {value: 6, url: '//deckofcardsapi.com/static/img/6H.png'}, 
        'H-7': {value: 7, url: '//deckofcardsapi.com/static/img/7H.png'}, 
        'H-8': {value: 8, url: '//deckofcardsapi.com/static/img/8H.png'}, 
        'H-9': {value: 9, url: '//deckofcardsapi.com/static/img/9H.png'}, 
        'H-J': {value: 10, url: '//deckofcardsapi.com/static/img/JH.png'}, 
        'H-Q': {value: 10, url: '//deckofcardsapi.com/static/img/QH.png'}, 
        'H-K': {value: 10, url: '//deckofcardsapi.com/static/img/KH.png'}, 
            'S-ace': {value: 1, url: '//deckofcardsapi.com/static/img/AS.png'}, 
            'S-2': {value: 2, url: '//deckofcardsapi.com/static/img/2S.png'},  
            'S-3': {value: 3, url: '//deckofcardsapi.com/static/img/3S.png'}, 
            'S-4': {value: 4, url: '//deckofcardsapi.com/static/img/4S.png'}, 
            'S-5': {value: 5, url: '//deckofcardsapi.com/static/img/5S.png'}, 
            'S-6': {value: 6, url: '//deckofcardsapi.com/static/img/6S.png'}, 
            'S-7': {value: 7, url: '//deckofcardsapi.com/static/img/7S.png'}, 
            'S-8': {value: 8, url: '//deckofcardsapi.com/static/img/8S.png'}, 
            'S-9': {value: 9, url: '//deckofcardsapi.com/static/img/9S.png'}, 
            'S-J': {value: 10, url: '//deckofcardsapi.com/static/img/JS.png'}, 
            'S-Q': {value: 10, url: '//deckofcardsapi.com/static/img/QS.png'}, 
            'S-K': {value: 10, url: '//deckofcardsapi.com/static/img/KS.png'}, 
        'C-ace': {value: 1, url: '//deckofcardsapi.com/static/img/AC.png'},
        'C-2': {value: 2, url: '//deckofcardsapi.com/static/img/2C.png'}, 
        'C-3': {value: 3, url: '//deckofcardsapi.com/static/img/3C.png'},  
        'C-4': {value: 4, url: '//deckofcardsapi.com/static/img/4C.png'},  
        'C-5': {value: 5, url: '//deckofcardsapi.com/static/img/5C.png'},  
        'C-6': {value: 6, url: '//deckofcardsapi.com/static/img/6C.png'}, 
        'C-7': {value: 7, url: '//deckofcardsapi.com/static/img/7C.png'}, 
        'C-8': {value: 8, url: '//deckofcardsapi.com/static/img/8C.png'}, 
        'C-9': {value: 9, url: '//deckofcardsapi.com/static/img/9C.png'}, 
        'C-J': {value: 10, url: '//deckofcardsapi.com/static/img/JC.png'}, 
        'C-Q': {value: 10, url: '//deckofcardsapi.com/static/img/QC.png'}, 
        'C-K': {value: 10, url: '//deckofcardsapi.com/static/img/KC.png'}, 
            'D-ace':  {value: 1, url: '//deckofcardsapi.com/static/img/AD.png'}, 
            'D-2': {value: 2, url: '//deckofcardsapi.com/static/img/2D.png'}, 
            'D-3': {value: 3, url: '//deckofcardsapi.com/static/img/3D.png'}, 
            'D-4': {value: 4, url: '//deckofcardsapi.com/static/img/4D.png'}, 
            'D-5': {value: 5, url: '//deckofcardsapi.com/static/img/5D.png'}, 
            'D-6': {value: 6, url: '//deckofcardsapi.com/static/img/6D.png'}, 
            'D-7': {value: 7, url: '//deckofcardsapi.com/static/img/7D.png'}, 
            'D-8': {value: 8, url: '//deckofcardsapi.com/static/img/8D.png'}, 
            'D-9': {value: 9, url: '//deckofcardsapi.com/static/img/9D.png'}, 
            'D-J': {value: 10, url: '//deckofcardsapi.com/static/img/JD.png'}, 
            'D-Q': {value: 10, url: '//deckofcardsapi.com/static/img/QD.png'}, 
            'D-K': {value: 10, url: '//deckofcardsapi.com/static/img/KD.png'}
    },
};